---
- name: Configure default server
  template: src=site-default.conf.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify: reload apache

- name: Disable default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload apache
  when: disable_default_site|default(false)

- name: Disable default-ssl site
  file:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    state: absent
  notify: reload apache
  when: disable_default_ssl_site|default(true)
