---
- name: Initialize Box
  hosts: all
  become: true
  roles:
    - { role: init, tags: [init] }

- name: Install hhighlighter
  hosts: all
  become: true
  roles:
    - { role: hhighlighter, tags: [hhighlighter] }
