---
- name: Register existing PHP-FPM pool configuration files
  shell: ls -1 /etc/php/7.0/fpm/pool.d
  register: pools_enabled
  changed_when: false

- name: Remove unused PHP-FPM pool configuration files
  file:
    path: "/etc/php/7.0/fpm/pool.d/{{ item }}"
    state: absent
  with_items: "{{ pools_enabled.stdout_lines }}"
  when: >
    item[:-5] not in sites | default([]) and
    item != "www.conf" and
    item != "www.disabled"
  notify: reload php-fpm

- name: Create PHP-FPM pool configuration files
  template:
    src: pool.conf.j2
    dest: "/etc/php/7.0/fpm/pool.d/{{ item.value.host }}.conf"
  with_dict: "{{ sites }}"
  notify: reload php-fpm
