---
- name: Install avahi related packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ avahi_packages }}"
  notify: restart avahi-daemon

- name: Install the avahi-alias python script
  copy:
    src: avahi-alias
    dest: /usr/sbin/avahi-alias
    owner: root
    group: root
    mode: 0755

- name: Register the avahi-alias service
  copy:
    src: avahi-alias.service
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Enable the avahi-alias service
  systemd:
    name: avahi-alias.service
    daemon_reload: yes
    enabled: yes

- name: Create avahi-alias config directory
  file:
    path: /etc/avahi/alias.d
    state: directory
    owner: root
    group: root
  notify: restart avahi-alias
