---
- name: Make sure the MySQL users are present
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default('pass') }}"
    priv: "{{ item.priv | default('*.*:ALL') }}"
    host: "{{ item.host | default('localhost') }}"
    state: present
    login_user: "{{ mysql_root_user | default('root') }}"
    login_password: "{{ mysql_root_password | default('pass') }}"
  with_items: "{{ mysql_users }}"
