---
- name: Install MariaDB MySQL server
  apt:
    name: ['mariadb-client', 'mariadb-server', 'python3-pymysql', 'python3-mysqldb']
    state: present

- name: Disable MariaDB binary logging
  when: mysql_disable_bin_log | default(false)
  copy:
    dest: /etc/mysql/conf.d/mysql_disable_bin_log.cnf
    content: |
      [mysqld]
      skip-log-bin
    owner: root
    group: root
  notify: restart mariadb

- name: Set root user password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket | default('/var/run/mysqld/mysqld.sock') }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL server users
  mysql_user:
    user: ""
    host: "{{ item }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket | default('/var/run/mysqld/mysqld.sock') }}"
    state: absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket | default('/var/run/mysqld/mysqld.sock') }}"
