---
- name: Create index files
  template:
    src: index.html.j2
    dest: "{{ www_root }}/{{ item.host }}/html/index.newsite.html"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0664
  with_items: "{{ virtualhost_sites }}"

- name: Create configuration files
  template:
    src: host.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.host }}.conf"
  with_items: "{{ virtualhost_sites }}"

- name: Link configuration files
  file:
    src: "/etc/apache2/sites-available/{{ item.host }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.host }}.conf"
    state: link
  with_items: "{{ virtualhost_sites }}"
  notify: reload apache
