---
- name: Make sure essential packages are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - build-essential
  - git
  - curl
  - rsync
  - ruby
  - dbus
  - libnss-myhostname

- name: Make sure rmate binary is present
  gem:
    name: rmate
    state: latest
    user_install: no
